### ISSUE TITLE
AttributeError: 'CAFE_fig' object has no attribute 'lambdas'

### ISSUE THREAD

**Issue by Matt-BF** [LKremer/CAFE_fig#2]
Hi,
I tried parsing my CAFE resultfile, but got an attribute error. Here is the traceback:
Traceback (most recent call last):
  File "../../scripts/CAFE_fig.py", line 509, in <module>
    main(**vars(args))
  File "../../scripts/CAFE_fig.py", line 454, in main
    c.summary_tree()
  File "../../scripts/CAFE_fig.py", line 291, in summary_tree
    min(self.lambdas.values()), max(self.lambdas.values()))
AttributeError: 'CAFE_fig' object has no attribute 'lambdas'

I am running python on a conda environment with:
pyqt                      4.11.4
python                  3.5.5
ete3                      3.0.0b35

Thanks in advance!

**Comment by LKremer** [comment]
Hi Matt, would you mind uploading your CAFE result file so I can try to reproduce this issue?
Best, Lukas

**Comment by Matt-BF** [comment]
Sure thing, here it is
[resultfile.cafe.gz](https://github.com/LKremer/CAFE_fig/files/2609304/resultfile.cafe.gz)

**Comment by LKremer** [comment]
Hi @Matt-BF ,
sorry for the delay, this is just to let you know I'm running into the exact same crash on my computer, so it's either a problem with your CAFE file or my script. I'll see if I can identify what's causing the issue!

**Comment by LKremer** [comment]
Hi @Matt-BF,
thanks for providing your file. I think I was able to fix the issue (see the commit above, the script no longer crashes on my end). Please pull or clone the repo again and try again :)

**Comment by Matt-BF** [comment]
Hi Lukas, I'm also sorry for the delay. I have just run the script on my desktop and pdf files are being written as expected! Thank you very much for the fix. However, when running the script on a remote server or cluster, ETE3 crashes because of a lack of Xserver support. I will try to find a workaround for this and will report if I find something useful
Thanks again!

**Comment by LKremer** [comment]
Hi Matt,
glad to hear that it works for you now! I remember running into the same remote server issues as you, but unfortunately this is out of my control because it's a limitation of ETE3.
What you can try to do is using the --dump option to directly write the figures to files instead of displaying them in a window. I think I tried the same in the past and I don't remember if it worked, but it's worth a shot!
