### ISSUE TITLE
module 'ete3' has no attribute 'TreeStyle'

### ISSUE THREAD

**Issue by Zhuxitong** [LKremer/CAFE_fig#3]
Conmand line I used:
```
python ~/softwares/CAFE_fig/CAFE_fig.py -d cafe_fig pan_genome_remove_atalla.cafe
```

The ete3 information:
```
pip list
Package      Version 
------------ --------
asn1crypto   0.24.0  
certifi      2019.3.9
cffi         1.11.5  
chardet      3.0.4   
conda        4.6.14  
cryptography 2.4.2   
ete3         3.0.0b35
```

Any suggestions are appreciative !

**Comment by LKremer** [comment]
Hi @Zhuxitong ,
this seems to be an issue with the installation of ete3. Maybe you don't have read and execute permissions in your ete3 installation directory?

**Comment by LKremer** [comment]
Did some research and it seems to be a problem with ete3 indeed:
https://github.com/etetoolkit/ete/issues/354
So this is beyond my control. In the link above they are discussing possible solutions.
Best,
Lukas

**Comment by cccsnd** [comment]
I have tried with the following PyQt5 version and it works!
"pip3 install PyQt5==5.11.3
it will work for sure!"
 from @himanshub84  
[https://github.com/etetoolkit/ete/issues/354](url)
